Class {
	#name : #GtCoderViewModelRecomputeAddOnRequest,
	#superclass : #Announcement,
	#instVars : [
		'coderViewModel'
	],
	#category : 'GToolkit-Coder-UI-Coder - Basic'
}

{ #category : #accessing }
GtCoderViewModelRecomputeAddOnRequest >> coderViewModel [
	^ coderViewModel
]

{ #category : #accessing }
GtCoderViewModelRecomputeAddOnRequest >> coderViewModel: anObject [
	coderViewModel := anObject
]
