"
An element to toggle an embedded expandable element within the text of the source coder. An examples can be an expandable method or a baseline name.
"
Class {
	#name : #GtSourceCoderEmbeddedExpanderToggleId,
	#superclass : #GtCoderElementId,
	#category : #'GToolkit-Coder-UI-Coder - Ids'
}

{ #category : #converting }
GtSourceCoderEmbeddedExpanderToggleId >> asSymbol [
	^ #'source-coder--embedded-expander-toggle'
]
