Class {
	#name : #GtTextualCoderViewModel,
	#superclass : #GtCoderUIModel,
	#instVars : [
		'hasFocus',
		'expanded',
		'stylers'
	],
	#category : #'GToolkit-Coder-UI-Coder - Textual Model'
}

{ #category : #'api - coder model' }
GtTextualCoderViewModel >> onCoderModelChanged [
	super onCoderModelChanged.
	
	
]

{ #category : #'api - coder model' }
GtTextualCoderViewModel >> subscribeToCoderModel [
	super subscribeToCoderModel.
	
	
]
