Class {
	#name : #GtTextualCoderViewModelRemoveHighlightsRequest,
	#superclass : #GtTextualCoderViewModelAnnouncement,
	#instVars : [
		'id'
	],
	#category : #'GToolkit-Coder-UI-Coder - Textual Model - Events'
}

{ #category : #accessing }
GtTextualCoderViewModelRemoveHighlightsRequest >> id [
	^ id
]

{ #category : #accessing }
GtTextualCoderViewModelRemoveHighlightsRequest >> id: anObject [
	id := anObject
]
