Class {
	#name : #GtCoderSourceString,
	#superclass : #Object,
	#instVars : [
		'string',
		'epoch'
	],
	#category : #'GToolkit-Coder-Promised'
}

{ #category : #accessing }
GtCoderSourceString >> epoch [

	^ epoch
]

{ #category : #accessing }
GtCoderSourceString >> epoch: anObject [

	epoch := anObject
]

{ #category : #accessing }
GtCoderSourceString >> string [

	^ string
]

{ #category : #accessing }
GtCoderSourceString >> string: anObject [

	string := anObject
]
