"
!What are the editor shortcuts?

What shortcuts are availabe in a method coder?

${example:GtMethodCoderExamples>>#emptyMethodCoder|previewShow=##gtLiveFor:|previewExpanded=|noCode=|previewHeight=100}$

These ones:

${example:GtMethodCoderExamples>>#emptyMethodCoder|previewShow=#gtViewKeybindingsFor:|previewExpanded=|noCode=}$

And what about a Playground snippet?

${example:GtPlaygroundPharoSnippetExamples>>#pharoSnippet|previewShow=#gtLiveFor:|previewHeight=100|noCode=}$

These ones.

${example:GtPlaygroundPharoSnippetExamples>>#pharoSnippet|previewShow=#gtKeybindingsFor:|previewHeight=400|noCode=}$

"
Class {
	#name : #GtCoderShortcutsExplanation,
	#superclass : #Object,
	#category : #'GToolkit-Coder-Examples-Basic'
}
