"
1. What are the editor shortcuts?

What shortcuts are availabe in a method coder?

{{gtExample:GtMethodCoderExamples>>#emptyMethodCoder|previewShow=##gtLiveFor:|previewExpanded=|noCode=|previewHeight=100}}

These ones:

{{gtExample:GtMethodCoderExamples>>#emptyMethodCoder|previewShow=#gtViewKeybindingsFor:|previewExpanded=|noCode=}}

And what about a Playground snippet?

{{gtExample:GtPlaygroundPharoSnippetExamples>>#pharoSnippet|previewShow=#gtLiveFor:|previewHeight=100|noCode=}}

These ones.

{{gtExample:GtPlaygroundPharoSnippetExamples>>#pharoSnippet|previewShow=#gtKeybindingsFor:|previewHeight=400|noCode=}}


"
Class {
	#name : #GtCoderShortcutsExplanation,
	#superclass : #Object,
	#category : #'GToolkit-Coder-Examples-! Explanation'
}
