Class {
	#name : #GtClassCoderMethodsNavigationAnnouncement,
	#superclass : #Announcement,
	#instVars : [
		'methods',
		'source'
	],
	#category : #'GToolkit-Coder-Event'
}

{ #category : #accessing }
GtClassCoderMethodsNavigationAnnouncement >> methods [
	^ methods
]

{ #category : #accessing }
GtClassCoderMethodsNavigationAnnouncement >> methods: anObject [
	methods := anObject
]

{ #category : #accessing }
GtClassCoderMethodsNavigationAnnouncement >> source [
	^ source
]

{ #category : #accessing }
GtClassCoderMethodsNavigationAnnouncement >> source: anObject [
	source := anObject
]
