Class {
	#name : #GtClassCoderMethodProtocolNavigationAnnouncement,
	#superclass : #Announcement,
	#instVars : [
		'methodProtocol'
	],
	#category : #'GToolkit-Coder-Event'
}

{ #category : #accessing }
GtClassCoderMethodProtocolNavigationAnnouncement >> methodProtocol [
	^ methodProtocol
]

{ #category : #accessing }
GtClassCoderMethodProtocolNavigationAnnouncement >> methodProtocol: anObject [
	methodProtocol := anObject
]
