Class {
	#name : #GtClassCoderSlotNavigationAnnouncement,
	#superclass : #Announcement,
	#instVars : [
		'slot',
		'source'
	],
	#category : #'GToolkit-Coder-Coders'
}

{ #category : #'as yet unclassified' }
GtClassCoderSlotNavigationAnnouncement >> slot [
	^ slot
]

{ #category : #accessing }
GtClassCoderSlotNavigationAnnouncement >> slot: aSlot [
	slot := aSlot
]

{ #category : #'as yet unclassified' }
GtClassCoderSlotNavigationAnnouncement >> source [
	^ source
]

{ #category : #accessing }
GtClassCoderSlotNavigationAnnouncement >> source: aSource [
	source := aSource
]
