Class {
	#name : 'GtClassCoderMethodProtocolNavigationAnnouncement',
	#superclass : 'Announcement',
	#instVars : [
		'methodProtocol',
		'source'
	],
	#category : 'GToolkit-Coder-Event'
}

{ #category : 'accessing' }
GtClassCoderMethodProtocolNavigationAnnouncement >> methodProtocol [
	^ methodProtocol
]

{ #category : 'accessing' }
GtClassCoderMethodProtocolNavigationAnnouncement >> methodProtocol: anObject [
	methodProtocol := anObject
]

{ #category : 'accessing' }
GtClassCoderMethodProtocolNavigationAnnouncement >> source [
	^ source
]

{ #category : 'accessing' }
GtClassCoderMethodProtocolNavigationAnnouncement >> source: anObject [
	source := anObject
]
