Class {
	#name : 'GtCoderNavigationPackageRenamed',
	#superclass : 'GtCoderNavigationPackageAnnoucement',
	#instVars : [
		'oldName',
		'newName'
	],
	#category : 'GToolkit-Coder-Navigation - Events'
}

{ #category : 'accessing' }
GtCoderNavigationPackageRenamed >> newName [
	^ newName
]

{ #category : 'accessing' }
GtCoderNavigationPackageRenamed >> newName: anObject [
	newName := anObject
]

{ #category : 'accessing' }
GtCoderNavigationPackageRenamed >> oldName [
	^ oldName
]

{ #category : 'accessing' }
GtCoderNavigationPackageRenamed >> oldName: anObject [
	oldName := anObject
]
