Class {
	#name : #GtCoderNavigationClassDeselected,
	#superclass : #GtCoderNavigationSelectionAnnouncement,
	#instVars : [
		'theClass'
	],
	#category : #'GToolkit-Coder-Navigation - Events'
}

{ #category : #accessing }
GtCoderNavigationClassDeselected >> theClass [
	<return: #Class>

	^ theClass
]

{ #category : #accessing }
GtCoderNavigationClassDeselected >> theClass: anObject [
	theClass := anObject
]
