Class {
	#name : 'GtCoderNavigationClassAnnoucement',
	#superclass : 'GtCoderNavigationSystemChangesAnnouncement',
	#instVars : [
		'package',
		'tag',
		'theClass'
	],
	#category : 'GToolkit-Coder-Navigation - Events'
}

{ #category : 'accessing' }
GtCoderNavigationClassAnnoucement >> package [
	^ package
]

{ #category : 'accessing' }
GtCoderNavigationClassAnnoucement >> package: anObject [
	package := anObject
]

{ #category : 'accessing' }
GtCoderNavigationClassAnnoucement >> tag [
	^ tag
]

{ #category : 'accessing' }
GtCoderNavigationClassAnnoucement >> tag: anObject [
	tag := anObject
]

{ #category : 'accessing' }
GtCoderNavigationClassAnnoucement >> theClass [
	^ theClass
]

{ #category : 'accessing' }
GtCoderNavigationClassAnnoucement >> theClass: anObject [
	theClass := anObject
]
