Class {
	#name : #GtCoderAst,
	#superclass : #Object,
	#instVars : [
		'ast',
		'epoch'
	],
	#category : #'GToolkit-Coder-Ast'
}

{ #category : #accessing }
GtCoderAst >> ast [

	^ ast
]

{ #category : #accessing }
GtCoderAst >> ast: anObject [

	ast := anObject
]

{ #category : #accessing }
GtCoderAst >> epoch [

	^ epoch
]

{ #category : #accessing }
GtCoderAst >> epoch: anObject [

	epoch := anObject
]
