Class {
	#name : 'GtCoderNavigationPackageTagAnnoucement',
	#superclass : 'GtCoderNavigationSystemChangesAnnouncement',
	#instVars : [
		'package',
		'tag'
	],
	#category : 'GToolkit-Coder-Navigation - Events'
}

{ #category : 'accessing' }
GtCoderNavigationPackageTagAnnoucement >> package [
	^ package
]

{ #category : 'accessing' }
GtCoderNavigationPackageTagAnnoucement >> package: anObject [
	package := anObject
]

{ #category : 'accessing' }
GtCoderNavigationPackageTagAnnoucement >> tag [
	^ tag
]

{ #category : 'accessing' }
GtCoderNavigationPackageTagAnnoucement >> tag: anObject [
	tag := anObject
]
